port: 12190
firewall: iptables  # iptables is default, can also use nftables

# Logging
log: stdout          # or /var/log/roco.log
log_level: info      # or debug

relays:
  - targets: ["qbtch2"]
    chain: ['qbtch7']

